content:
  - name: aktualnosci
    label: Aktualności
    type: file
    path: content/aktualnosci.json
    format: json
    operations:
      delete: false
    fields:
      - name: items
        label: Ogłoszenia
        description: Aby dodać nowe ogłoszenie, kliknij przycisk „Add an item” poniżej.
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{title}"
        fields:
          - name: title
            label: Tytuł
            type: string
            required: true
          - name: date
            label: Data
            type: date
            required: true
            description: Nowsza data oznacza wyższą pozycję na stronie.
            options:
              time: false
              format: yyyy-MM-dd
          - name: body
            label: Treść
            type: text
            required: true
          - name: published
            label: Opublikowane
            type: boolean
            default: false
